version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: journiz/journiz-server
          registry: ghcr.io
          executor:
            machine:
              image: ubuntu-2004:current
          docker-password: GITHUB_TOKEN
          docker-username: CIRCLE_PROJECT_USERNAME
          tag: circleci
