version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
workflows:
  build-and-publish-docker-image:
    resource-class: arm.medium
    jobs:
      - docker/publish:
          image: journiz/journiz-server
          registry: ghcr.io
          docker-password: GITHUB_TOKEN
          docker-username: CIRCLE_PROJECT_USERNAME
          tag: circleci
