# .circleci/config.yml
version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - docker/build:
          image: journiz/journiz-server
          tag: circleci
          dockerfile: Dockerfile
          context: .
          use-buildkit: true
          registry: ghcr.io
          cache-from: journiz/journiz-server
