version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: ghcr.io
          docker-password: $GITHUB_TOKEN
          docker-username: $CIRCLE_PROJECT_USERNAME
          tag: circleci
