version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - name: Docker Login
        run: echo "${GITHUB_TOKEN}" | docker login -u $CIRCLE_PROJECT_USERNAME --password-stdin ghcr.io

      - docker/build:
          image: journiz/journiz-server
          tag: circleci
          dockerfile: Dockerfile
          use-buildkit: true
          registry: ghcr.io
          cache_from: journiz/journiz-server
      - docker/push:
          image: journiz/journiz-server
          tag: circleci
          registry: ghcr.io
