version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: echo "${GITHUB_TOKEN}" | docker login -u $CIRCLE_PROJECT_USERNAME --password-stdin ghcr.io
      - docker/build:
          image: journiz/journiz-server
          tag: $CIRCLE_BRANCH
          dockerfile: Dockerfile
          use-buildkit: true
          registry: ghcr.io
          cache_from: "ghcr.io/journiz/journiz-server:$CIRCLE_BRANCH"
      - docker/push:
          image: journiz/journiz-server
          tag: $CIRCLE_BRANCH
          registry: ghcr.io

  trigger-pull:
    machine:
      enabled: true
    steps:
      - run:
          name: Trigger pull on server
          command: |
            ssh $SSH_USER@$SSH_HOST "~/scripts/deploy_$CIRCLE_BRANCH.sh"

workflows:
  build-and-deploy:
    jobs:
      - build
      - trigger-pull:
          requires:
            - build
#        filters:
#          branches:
#            only: main # only deploy on the main branch

